const _keyboards = {
  "VK_LCONTROL": false,
  "VK_RCONTROL": false,
  "VK_LMENU": false,
  "VK_RMENU": false,

  "VK_LSHIFT": false,
  "VK_RSHIFT": false,
 
  "VK_LWIN": false,
  "VK_RWIN": false,
  
  "VK_BACK": false,
  "VK_TAB": false,
  "VK_CLEAR": false,
  "VK_RETURN": false,
  "VK_SHIFT": false,
  "VK_CONTROL": false,
  "VK_MENU": false,
  "VK_PAUSE": false,
  "VK_CAPITAL": false,
  "VK_ESCAPE": false,
  "VK_SPACE": false,
  "VK_PRIOR": false,
  "VK_NEXT": false,
  "VK_END": false,
  "VK_HOME": false,
  "VK_LEFT": false,
  "VK_UP": false,
  "VK_RIGHT": false,
  "VK_DOWN": false,
  "VK_SELECT": false,
  "VK_PRINT": false,
  "VK_EXECUTE": false,
  "VK_SNAPSHOT": false,
  "VK_INSERT": false,
  "VK_DELETE": false,
  "VK_HELP": false,

  "VK_0": false,
  "VK_1": false,
  "VK_2": false,
  "VK_3": false,
  "VK_4": false,
  "VK_5": false,
  "VK_6": false,
  "VK_7": false,
  "VK_8": false,
  "VK_9": false,

  "VK_A": false,
  "VK_B": false,
  "VK_C": false,
  "VK_D": false,
  "VK_E": false,
  "VK_F": false,
  "VK_G": false,
  "VK_H": false,
  "VK_I": false,
  "VK_J": false,
  "VK_K": false,
  "VK_L": false,
  "VK_M": false,
  "VK_N": false,
  "VK_O": false,
  "VK_P": false,
  "VK_Q": false,
  "VK_R": false,
  "VK_S": false,
  "VK_T": false,
  "VK_U": false,
  "VK_V": false,
  "VK_W": false,
  "VK_X": false,
  "VK_Y": false,
  "VK_Z": false,

  "VK_NUMPAD0": false,
  "VK_NUMPAD1": false,
  "VK_NUMPAD2": false,
  "VK_NUMPAD3": false,
  "VK_NUMPAD4": false,
  "VK_NUMPAD5": false,
  "VK_NUMPAD6": false,
  "VK_NUMPAD7": false,
  "VK_NUMPAD8": false,
  "VK_NUMPAD9": false,
  "VK_MULTIPLY": false,
 
  "VK_F1": false,
  "VK_F2": false,
  "VK_F3": false,
  "VK_F4": false,
  "VK_F5": false,
  "VK_F6": false,
  "VK_F7": false,
  "VK_F8": false,
  "VK_F9": false,
  "VK_F10": false,
  "VK_F11": false,
  "VK_F12": false,
};

const specialKeysMap = {
  "VK_LCONTROL": "Ctrl",
  "VK_RCONTROL": "Ctrl",
  "VK_LSHIFT": "Shift",
  "VK_RSHIFT": "Shift",
  "VK_LMENU": "Alt", 
  "VK_RMENU": "Alt",
  "VK_LWIN": "Win",
  "VK_RWIN": "Win",
  "VK_APPS": "Menu",
  "VK_CAPITAL": "CapsLock",
  "VK_NUMLOCK": "NumLock",
  "VK_SCROLL": "ScrollLock"
}

module.exports = {
  _keyboards,
  specialKeysMap
};

export interface KeyCombine {
  focus: Function | undefined
  blur: Function | undefined
}